apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector: 
    component: web
  ports:
      # Port on the service
    - port: 3000
      # Port in the container
      targetPort: 3000