apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector: 
    component: postgres
  ports:
      # Port on the service
    - port: 5432
      # Port in the container
      targetPort: 5432