apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector: 
    component: server
  ports:
      # Port on the service
    - port: 5000
      # Port in the container
      targetPort: 5000